name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore ./Code/Synnotech.Time.sln
    - name: Build
      run: dotnet build ./Code/Synnotech.Time.sln --no-restore -c Release
    - name: Test
      run: dotnet test ./Code/Synnotech.Time.Tests/Synnotech.Time.Tests.csproj --no-build --verbosity normal -c Release
